Repository konflux-ci/community-catalog, pull requests merged in 2025-07, with the labels that each got.

#27 feat(RELEASE-1691): add task check-if-related-test
  tasks/check-if-related-test/OWNERS
  tasks/check-if-related-test/README.md
  tasks/check-if-related-test/check-if-related-test.yaml
  tasks/check-if-related-test/tests/mocks.sh
  tasks/check-if-related-test/tests/pre-apply-task-hook.sh
  tasks/check-if-related-test/tests/test-check-if-related-test.yaml
Labels: approved

#24 feat(CNF-18687): Implement FBC image resolvability pipeline
  pipelines/validate-fbc-images-resolvable/OWNERS
  pipelines/validate-fbc-images-resolvable/README.md
  pipelines/validate-fbc-images-resolvable/validate-fbc-images-resolvable.yaml
  tasks/download-file-from-git-repo/OWNERS
  tasks/download-file-from-git-repo/README.md
  tasks/download-file-from-git-repo/download-file-from-git-repo.yaml
  tasks/download-file-from-git-repo/tests/README.md
  tasks/download-file-from-git-repo/tests/mocks.sh
  tasks/download-file-from-git-repo/tests/pre-apply-task-hook.sh
  tasks/download-file-from-git-repo/tests/test-download-file-404.yaml
  tasks/download-file-from-git-repo/tests/test-download-file-empty.yaml
  tasks/download-file-from-git-repo/tests/test-download-file-invalid-key.yaml
  tasks/download-file-from-git-repo/tests/test-download-file-missing-secret.yaml
  tasks/download-file-from-git-repo/tests/test-download-file-private-github.yaml
  tasks/download-file-from-git-repo/tests/test-download-file-private-gitlab.yaml
  tasks/download-file-from-git-repo/tests/test-download-file-public-github.yaml
  tasks/download-file-from-git-repo/tests/test-download-file-public-gitlab.yaml
  tasks/download-file-from-git-repo/tests/test-download-file-unknown-provider.yaml
  tasks/validate-fbc-images-resolvable/OWNERS
  tasks/validate-fbc-images-resolvable/README.md
  tasks/validate-fbc-images-resolvable/tests/mocks.sh
  tasks/validate-fbc-images-resolvable/tests/pre-apply-task-hook.sh
  tasks/validate-fbc-images-resolvable/tests/test-validate-fbc-empty-image.yaml
  tasks/validate-fbc-images-resolvable/tests/test-validate-fbc-no-images.yaml
  tasks/validate-fbc-images-resolvable/tests/test-validate-fbc-partial-mirror.yaml
  tasks/validate-fbc-images-resolvable/tests/test-validate-fbc-retry.yaml
  tasks/validate-fbc-images-resolvable/tests/test-validate-fbc-success.yaml
  tasks/validate-fbc-images-resolvable/tests/test-validate-fbc-unavailable-images.yaml
  tasks/validate-fbc-images-resolvable/tests/test-validate-fbc-with-mirrors.yaml
  tasks/validate-fbc-images-resolvable/validate-fbc-images-resolvable.yaml
Labels: approved, ok-to-test

#29 chore(CNF-18687): update task resolution to upstream branch
  pipelines/validate-fbc-images-resolvable/validate-fbc-images-resolvable.yaml
Labels: approved, lgtm

#22 feat(RELEASE-1725): auto generate README.md files for tasks/pipelines
  .github/scripts/check_readme.sh
  .github/scripts/readme_generator.sh
  pipelines/notify-slack-on-failure/README.md
  pipelines/notify-slack-on-failure/notify-slack-on-failure.yaml
  pipelines/push-snapshot-to-quay/README.md
  pipelines/push-snapshot-to-quay/push-snapshot-to-quay.yaml
  pipelines/update-internal-services-manager/README.md
  pipelines/update-internal-services-manager/update-internal-services-manager.yaml
  tasks/get-git-sha-image-ref-from-release/README.md
  tasks/get-git-sha-image-ref-from-release/get-git-sha-image-ref-from-release.yaml
  tasks/notify-slack-on-failure/README.md
  tasks/notify-slack-on-failure/notify-slack-on-failure.yaml
  tasks/push-snapshot-to-quay/README.md
  tasks/push-snapshot-to-quay/push-snapshot-to-quay.yaml
  tasks/update-manager-image-in-git/update-manager-image-in-git.yaml
Labels: approved, lgtm

#25 feat(RELEASE-1493): add user documentation to community-catalog
  CONTRIBUTING.md
  LICENSE
  README.md
  pull_request_template.md
Labels: approved, lgtm

#39 docs: add testing info to CONTRIBUTING.md
  .github/scripts/test_tekton_tasks.sh
  CONTRIBUTING.md
Labels: approved, lgtm
